### ISSUE TITLE
Parameterise group names

### ISSUE THREAD

**Issue by declension** [FormidableLabs/terraform-aws-serverless#25]
Hi, thanks for what looks like a very useful project!

The existing `admin`, `developer`, `ci` are fairly good / safe names, but it would be good if users could customise (or: translate!) these.

For example, I'd like our `ci` ~user~ group to be called something else on account of an existing `ci` _environment_ (~=stage here I guess), leading to weird `tf-service-name-ci-ci` names.

**Comment by declension** [comment]
I think I'm now confused about what you mean, but perhaps I need to follow through with the implementation a bit first.

Outputs aside (which I'm sure would be useful, though as you say in the docs, we can just assign these roles manually for now), the issue is more auditing our AWS setup itself, with the naming present there, with AWS names like `tf-my-service-ci-ci` etc...

**Comment by ryan-roemer** [comment]
Yeah, auditing would favor having the change permeate everything and not just the specific group names. I’ll see what I can work up...
